# Generated by Django 3.2.6 on 2023-10-01 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('thumbnail_size', models.CharField(max_length=20)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_upload.image')),
            ],
        ),
    ]
