# Generated by Django 3.2.6 on 2023-10-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0004_thumbnailimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnailimage',
            name='thumbnail_size',
            field=models.PositiveIntegerField(),
        ),
    ]
